 name: PHP 8 Environment Setup
  hosts: all
  become: true
  tasks:
    - name: Add PHP 8 repository
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PHP 8 packages
      apt:
        name:
          - php8.0-fpm
          - php8.0-gd
          - php8.0-mbstring
          - php8.0-mysql
          - php8.0-opcache
          - php8.0-zip
        state: present

    - name: Set PHP 7.2 as default
      alternatives:
        name: php
        path: /usr/bin/php7.2
        priority: 72
